language: python
python:
  - "2.7"
install:
  - pip install -r trequirements.txt
before_script:
  - python manage.py syncdb –migrate –noinput
script:
  - py.test --cov links --cov-report term-missing
after_success:
  - coveralls