language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput
script:
  - py.test --cov links --cov-report term-missing
after_success:
  - coveralls