language: python
python:
  - "2.7"
install:
  - pip install -e . --use-mirrors
before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - py.test --cov links --cov-report term-missing
after_success:
  - coveralls